<a href="https://colab.research.google.com/github/duellal/DS-Unit-1-Sprint-2-Statistics/blob/master/Duell_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
from zipfile import ZipFile

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-12-08 16:55:36--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.1’

student.zip.1       100%[===================>]  20.00K  --.-KB/s    in 0.06s   

2020-12-08 16:55:36 (310 KB/s) - ‘student.zip.1’ saved [20478/20478]



In [ ]:
with ZipFile('student.zip') as zip:
  zip.extract(member='student-mat.csv')


  df = zip.read('student-mat.csv')

df

b'school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3\n"GP";"F";18;"U";"GT3";"A";4;4;"at_home";"teacher";"course";"mother";2;2;0;"yes";"no";"no";"no";"yes";"yes";"no";"no";4;3;4;1;1;3;6;"5";"6";6\n"GP";"F";17;"U";"GT3";"T";1;1;"at_home";"other";"course";"father";1;2;0;"no";"yes";"no";"no";"no";"yes";"yes";"no";5;3;3;1;1;3;4;"5";"5";6\n"GP";"F";15;"U";"LE3";"T";1;1;"at_home";"other";"other";"mother";1;2;3;"yes";"no";"yes";"no";"yes";"yes";"yes";"no";4;3;2;2;3;3;10;"7";"8";10\n"GP";"F";15;"U";"GT3";"T";4;2;"health";"services";"home";"mother";1;3;0;"no";"yes";"yes";"yes";"yes";"yes";"yes";"yes";3;2;2;1;1;5;2;"15";"14";15\n"GP";"F";16;"U";"GT3";"T";3;3;"other";"other";"home";"father";1;2;0;"no";"yes";"yes";"no";"yes";"yes";"no";"no";4;3;2;1;2;5;4;"6";"10";10\n"GP";"M";16;"U";"LE3";"T";4;3;"services";"other";"reputati

In [ ]:
col = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Med', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime',
       'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 
       'freetime', 'go-out', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

df = pd.read_csv('student-mat.csv', sep=';')
df.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
df.describe() 

age        Medu        Fedu  ...          G1          G2          G3
count  395.000000  395.000000  395.000000  ...  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519  ...   10.908861   10.713924   10.415190
std      1.276043    1.094735    1.088201  ...    3.319195    3.761505    4.581443
min     15.000000    0.000000    0.000000  ...    3.000000    0.000000    0.000000
25%     16.000000    2.000000    2.000000  ...    8.000000    9.000000    8.000000
50%     17.000000    3.000000    2.000000  ...   11.000000   11.000000   11.000000
75%     18.000000    4.000000    3.000000  ...   13.000000   13.000000   14.000000
max     22.000000    4.000000    4.000000  ...   19.000000   19.000000   20.000000

[8 rows x 16 columns]

In [ ]:
df.describe(exclude='number')

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

In [ ]:
df['sex'].value_counts()

F    208
M    187
Name: sex, dtype: int64

In [ ]:
obs = pd.crosstab(df['traveltime'], df['absences'])

obs

absences    0   1   2   3   4   5   6   7   ...  26  28  30  38  40  54  56  75
traveltime                                  ...                                
1           74   2  40   5  37   4  16   5  ...   0   1   0   0   1   1   1   0
2           32   1  20   2  13   1  10   1  ...   1   0   1   1   0   0   0   1
3            6   0   4   1   3   0   3   1  ...   0   0   0   0   0   0   0   0
4            3   0   1   0   0   0   2   0  ...   0   0   0   0   0   0   0   0

[4 rows x 34 columns]

In [ ]:
stats.chi2_contingency(obs)

(61.11558335253091,
 0.9990069240658936,
 99,
 array([[7.48227848e+01, 1.95189873e+00, 4.22911392e+01, 5.20506329e+00,
         3.44835443e+01, 3.25316456e+00, 2.01696203e+01, 4.55443038e+00,
         1.43139241e+01, 1.95189873e+00, 1.10607595e+01, 1.95189873e+00,
         7.80759494e+00, 1.95189873e+00, 7.80759494e+00, 1.95189873e+00,
         4.55443038e+00, 6.50632911e-01, 3.25316456e+00, 6.50632911e-01,
         2.60253165e+00, 6.50632911e-01, 1.95189873e+00, 6.50632911e-01,
         6.50632911e-01, 6.50632911e-01, 6.50632911e-01, 6.50632911e-01,
         6.50632911e-01, 6.50632911e-01, 6.50632911e-01, 6.50632911e-01,
         6.50632911e-01, 6.50632911e-01],
        [3.11518987e+01, 8.12658228e-01, 1.76075949e+01, 2.16708861e+00,
         1.43569620e+01, 1.35443038e+00, 8.39746835e+00, 1.89620253e+00,
         5.95949367e+00, 8.12658228e-01, 4.60506329e+00, 8.12658228e-01,
         3.25063291e+00, 8.12658228e-01, 3.25063291e+00, 8.12658228e-01,
         1.89620253e+00, 2.70886076e

In [ ]:
obs2 = pd.crosstab(df['age'], df['failures'])

obs2

failures   0   1  2  3
age                   
15        71   3  5  3
16        88  10  4  2
17        84   8  2  4
18        63  16  1  2
19         5  13  3  3
20         1   0  2  0
21         0   0  0  1
22         0   0  0  1

In [ ]:
stats.chi2_contingency(obs2)

(144.29903924777085,
 2.1137084383846074e-20,
 21,
 array([[6.47696203e+01, 1.03797468e+01, 3.52911392e+00, 3.32151899e+00],
        [8.21468354e+01, 1.31645570e+01, 4.47594937e+00, 4.21265823e+00],
        [7.74075949e+01, 1.24050633e+01, 4.21772152e+00, 3.96962025e+00],
        [6.47696203e+01, 1.03797468e+01, 3.52911392e+00, 3.32151899e+00],
        [1.89569620e+01, 3.03797468e+00, 1.03291139e+00, 9.72151899e-01],
        [2.36962025e+00, 3.79746835e-01, 1.29113924e-01, 1.21518987e-01],
        [7.89873418e-01, 1.26582278e-01, 4.30379747e-02, 4.05063291e-02],
        [7.89873418e-01, 1.26582278e-01, 4.30379747e-02, 4.05063291e-02]]))

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
obs_margin = pd.crosstab(df['traveltime'], df['absences'], margins=True)

print(obs_margin.shape)
obs_margin


(5, 35)


absences      0  1   2  3   4  5   6  7  ...  28  30  38  40  54  56  75  All
traveltime                               ...                                 
1            74  2  40  5  37  4  16  5  ...   1   0   0   1   1   1   0  257
2            32  1  20  2  13  1  10  1  ...   0   1   1   0   0   0   1  107
3             6  0   4  1   3  0   3  1  ...   0   0   0   0   0   0   0   23
4             3  0   1  0   0  0   2  0  ...   0   0   0   0   0   0   0    8
All         115  3  65  8  53  5  31  7  ...   1   1   1   1   1   1   1  395

[5 rows x 35 columns]

In [ ]:
row_sums = obs_margin.iloc[0:4, 34:].values
row_sums = row_sums.T[0]

row_sums

array([257, 107,  23,   8])

In [ ]:
col_sums = obs_margin.iloc[4:, 0:34].values
col_sums = col_sums[0]

col_sums

array([115,   3,  65,   8,  53,   5,  31,   7,  22,   3,  17,   3,  12,
         3,  12,   3,   7,   1,   5,   1,   4,   1,   3,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1])

In [ ]:
total = df.shape[0]
total

395

In [ ]:
expected = []
for i in range(len(row_sums)):
  expected_row = []
  for column in col_sums:
    expected_val = column*row_sums[i]/total
    expected_row.append(expected_val)
  expected.append(expected_row)
 
  expect = np.array(expected)
  print(expect.shape)
  print(expect)


(1, 34)
[[74.82278481  1.95189873 42.29113924  5.20506329 34.4835443   3.25316456
  20.16962025  4.55443038 14.31392405  1.95189873 11.06075949  1.95189873
   7.80759494  1.95189873  7.80759494  1.95189873  4.55443038  0.65063291
   3.25316456  0.65063291  2.60253165  0.65063291  1.95189873  0.65063291
   0.65063291  0.65063291  0.65063291  0.65063291  0.65063291  0.65063291
   0.65063291  0.65063291  0.65063291  0.65063291]]
(2, 34)
[[74.82278481  1.95189873 42.29113924  5.20506329 34.4835443   3.25316456
  20.16962025  4.55443038 14.31392405  1.95189873 11.06075949  1.95189873
   7.80759494  1.95189873  7.80759494  1.95189873  4.55443038  0.65063291
   3.25316456  0.65063291  2.60253165  0.65063291  1.95189873  0.65063291
   0.65063291  0.65063291  0.65063291  0.65063291  0.65063291  0.65063291
   0.65063291  0.65063291  0.65063291  0.65063291]
 [31.15189873  0.81265823 17.60759494  2.16708861 14.35696203  1.35443038
   8.39746835  1.89620253  5.95949367  0.81265823  4.60506329  0.81

In [ ]:
chi2 = ((obs - expect)**2/expect).sum().sum()
chi2

61.11558335253092

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

A sample estimate is a small size of the population that you are looking at for a variable. It should give you a good estimate of the variable for the whole population.

- What are hypothesis test? How are they useful?

Hypothesis tests are tests where you see if the results of a certain study have happened by chance, aka: the validity of the claim. This is testing the null hypothesis and seeing if there is significant data to back up that the claim is true or not. There are 5 steps: 1. Creating a Null hypothesis, 2. Creating an alternative hypothesis, 3. Stating the confidence level, 4. Calculating the t-statistic and the p-value, and 5. Stating the conclusion.

- What is a "null hypothesis?"

A null hypothesis states that there is no relationship in the given data values. This reflects that any relationship in the sample is based on chance.

- What is a p-value and what does it represent?

The p-value is the probability for the null hypothesis. The larger the p-value, you should accept the null hypothesis. The lower the p-value, you should reject the null hypothesis and choose the alternative hypothesis. You compare your p-value to the confidence level that you selected in step 3.

- What does it mean for something to be "statistically significant?"

For something to be "statistically significant" it means that, in the case of the p-value, the probability that the null hypothesis is true is very slim when the p-value is small compared to the confidence level.

- What is a test statistic and how does it relate to a p-value?

A test statistic takes the data from the sample and compares it to what was expected. The lower the test statistic, the more likely you will accept the null hypothesis. The higher the test statistic, the more likely you will reject the null hypothesis and accept the alternative hypothesis.

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

Degrees of freedom is the sample size you are using. In a 1 sample test for independence, the degrees of freedom are calculated by subtracting 1 from the sample size; $n - 1$. In a 2 sample test for independence, the degrees of freedom are calculated by adding the two sample sizes together and subtracting by 2; $(n_1 + n_2) - 2$.
In a $\chi^2$ sample test for independence, the degrees of freedom are calculated by the number of rows minus 1, times the number of columns minus 1; $r = rows, c = columns: (r-1)(c-1)$.

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)